title: mkix0x
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 5
paginate_path: /blog/page:num/
show_excerpts: false

collections:
  posts:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: false
      comments: false
      share: false
      related: false

theme: minima
minima:
  skin: dark
  social_links:
    - { platform: twitter,        user_url: "https://twitter.com/mkix0x" }



