title: mkix0x
theme: minima
theme_color: "#333"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: /blog/page:num/
collections:
  posts:
    output: true
    permalink: /:collection/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      comments: true
      share: true
      related: true
      related_limit: 3
      related_heading: "Related Posts"
